### ISSUE TITLE
Idling & Undling Jenkins breaks sync plugin

### ISSUE THREAD

**Issue by vpavlin** [openshift/jenkins-sync-plugin#124]
I wrote a simple experimental script to watch for new builds and hit Jenkins instance to make sure it's woken up in case of it being idled (https://github.com/vpavlin/jenkins-waker), but Jenkins fails to run new builds after being unidled.

#### Steps to reproduce:
1. Create new pipeline
2. Run a build
3. When finished, `oc idle jenkins`
4. Run a new build
5. Hit https://jenkins-...../login
6. Check Jenkins pod logs

#### Expected results:
Jenkins figures that there is already a buildconfig initialised and just kicks of new build

#### Current results:

Jenkins fails with this error:
```
Mar 03, 2017 8:04:11 AM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher onInitialBuildConfigs
SEVERE: Failed to update job
java.lang.IllegalArgumentException: rest2-rest-springboot-tomcat already exists
	at hudson.model.Items.verifyItemDoesNotAlreadyExist(Items.java:462)
	at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:263)
	at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3781)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:214)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:159)
	at hudson.security.ACL.impersonate(ACL.java:221)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfigWatcher.java:159)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.onInitialBuildConfigs(BuildConfigWatcher.java:129)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.access$200(BuildConfigWatcher.java:65)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.doRun(BuildConfigWatcher.java:88)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bparees** [comment]
I'm pretty sure @gabemontero just fixed this, can you grab a new jenkins centos image?

**Comment by gabemontero** [comment]
Yep that is https://github.com/openshift/jenkins-sync-plugin/issues/117 ... the latest jenkins centos images on dockerhub have the fix ... you need version 0.1.8 or higher of openshift-sync plugin.

**Comment by vpavlin** [comment]
Thanks, it works with new image
