### ISSUE TITLE
NPE through new getAuthenticatedOpenShiftClient() path

### ISSUE THREAD

**Issue by gabemontero** [openshift/jenkins-sync-plugin#132]
Steps to reproduce

1) oc cluster up
2) oc new-app jenkins-ephemeral
3) from origin dir, oc new-app -f test/extended/testdata/samplepipeline-withenvs.yaml 
4) oc start-build sample-pipeline-withenvs
5) then go to "Configure System", and add an env var to the maven pod template for the k8s cloud plugin

Then see this in the jenkins log:

```
May 08, 2017 8:46:05 PM INFO io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration$1 doRun
Waiting for Jenkins to be started
May 08, 2017 8:46:05 PM INFO io.fabric8.jenkins.openshiftsync.BuildConfigWatcher start
Now handling startup build configs!!
May 08, 2017 8:46:05 PM SEVERE io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1 doRun
Failed to load BuildConfigs: java.lang.NullPointerException
java.lang.NullPointerException
	at com.cloudbees.plugins.credentials.matchers.IdMatcher.<init>(IdMatcher.java:56)
	at com.cloudbees.plugins.credentials.CredentialsMatchers.withId(CredentialsMatchers.java:132)
	at io.fabric8.jenkins.openshiftsync.CredentialsUtils.getCurrentToken(CredentialsUtils.java:76)
	at io.fabric8.jenkins.openshiftsync.OpenShiftUtils.getAuthenticatedOpenShiftClient(OpenShiftUtils.java:97)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.doRun(BuildConfigWatcher.java:98)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

May 08, 2017 8:46:05 PM SEVERE io.fabric8.jenkins.openshiftsync.BuildWatcher$1 doRun
Failed to load initial Builds: java.lang.NullPointerException
java.lang.NullPointerException
	at com.cloudbees.plugins.credentials.matchers.IdMatcher.<init>(IdMatcher.java:56)
	at com.cloudbees.plugins.credentials.CredentialsMatchers.withId(CredentialsMatchers.java:132)
	at io.fabric8.jenkins.openshiftsync.CredentialsUtils.getCurrentToken(CredentialsUtils.java:76)
	at io.fabric8.jenkins.openshiftsync.OpenShiftUtils.getAuthenticatedOpenShiftClient(OpenShiftUtils.java:97)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:77)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Feed    All    > SEVERE    > WARNING
```

And you can no longer start pipeline builds from `oc start-build`.

@bparees fyi

**Comment by bparees** [comment]
I would have guessed this was related to the credential changes @oatmealraisin introduced, but they went in a while ago and this should be getting exercised by our nightly pipeline extended build tests...

**Comment by bparees** [comment]
ah, we don't add env vars to pods as part of the extended tests.

**Comment by gabemontero** [comment]
Yes it is related to @oatmealraisin 's change, that is why I assigned it to him.

There is some change introduced to Jenkins' runtime by my editing of the maven slave pod template that causes this to occur.  Our current extended tests don't change the settings of the maven slave pod template.

But that config change breaks an assumption somewhere in that credentials path.

**Comment by gabemontero** [comment]
It could be a timing issue as the config change seems to have caused a recycling of Jenkins ... note the `Waiting for Jenkins to be started` just prior to the NPEs.  Perhaps we have to wait for something to be non-null or fully initialized before calling `CredentialsUtils.getCurrentToken`.
