### ISSUE TITLE
intermittent NPE after commit https://github.com/openshift/jenkins-sync-plugin/commit/47e0f4497c1b3f5468217d3982d371f1bbeb26e2

### ISSUE THREAD

**Issue by gabemontero** [openshift/jenkins-sync-plugin#136]
@oatmealraisin - unfortunately, this does not appear to be consistent.  But I've seen this error occasionally (twice running locally, once with extended tests on ci.openshift) when instantiating `samplepipeline-withenvs.yaml` from the `test/extended/testdata` directory in origin and running builds. 

But all of them have occurred since I updated the jenkins image with the sync plugin version containing https://github.com/openshift/jenkins-sync-plugin/commit/47e0f4497c1b3f5468217d3982d371f1bbeb26e2

Failed to load initial Builds: java.lang.NullPointerException
java.lang.NullPointerException
	at com.cloudbees.plugins.credentials.matchers.IdMatcher.<init>(IdMatcher.java:56)
	at com.cloudbees.plugins.credentials.CredentialsMatchers.withId(CredentialsMatchers.java:132)
	at io.fabric8.jenkins.openshiftsync.CredentialsUtils.getCurrentToken(CredentialsUtils.java:76)
	at io.fabric8.jenkins.openshiftsync.OpenShiftUtils.getAuthenticatedOpenShiftClient(OpenShiftUtils.java:97)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:77)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

See if you can infer the protection to prevent this from the stack trace.  If it is not obvious, we can huddle up and see if we can decipher anything.

Or hopefully some scenario arises where it occurs more consistently to facilitate debug.

**Comment by gabemontero** [comment]
actually, looking at the line numbers, I believe this was in fact missing https://github.com/openshift/jenkins-sync-plugin/commit/47e0f4497c1b3f5468217d3982d371f1bbeb26e2 ... I must have gotten the chain of events confused wrt the image updates.

Closing out - if something similar pops up will reopen.
