### ISSUE TITLE
ImageStreamWatcher exception when no annotations present

### ISSUE THREAD

**Issue by jwmullally** [openshift/jenkins-sync-plugin#146]
This ImageStream config raises the following exception (both during eventReceived and onInitialImageStream). Looks like ImageStreamWatcher needs to handle the case where "label role=jenkins-slave" is set, but no annotation map exists.

Imported using: `oc create -f <file.yaml>`

```
apiVersion: v1
kind: ImageStream
metadata:
  name: jenkins-slave-custom-centos7
  labels:
    role: jenkins-slave
```
```
Jun 20, 2017 6:48:05 PM io.fabric8.jenkins.openshiftsync.ImageStreamWatcher eventReceived
WARNING: Caught: java.lang.NullPointerException
java.lang.NullPointerException
	at io.fabric8.jenkins.openshiftsync.ImageStreamWatcher.podTemplateFromData(ImageStreamWatcher.java:202)
	at io.fabric8.jenkins.openshiftsync.ImageStreamWatcher.podTemplates(ImageStreamWatcher.java:174)
	at io.fabric8.jenkins.openshiftsync.ImageStreamWatcher.eventReceived(ImageStreamWatcher.java:86)
	at io.fabric8.jenkins.openshiftsync.ImageStreamWatcher.eventReceived(ImageStreamWatcher.java:40)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:251)
	at okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
	at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
	at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
	at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
	at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
```

This works OK:
```
apiVersion: v1
kind: ImageStream
metadata:
  name: jenkins-slave-custom-centos7
  labels:
    role: jenkins-slave
  annotations:
    myvalue: abc
```
```
Jun 20, 2017 6:48:13 PM io.fabric8.jenkins.openshiftsync.JenkinsUtils addPodTemplate
INFO: Adding PodTemplate: jenkins-slave-custom-centos7
```

Versions (everything should be latest as of 2017-06-20)
```
$ oc process openshift//jenkins-persistent | oc create -f -

$ sudo docker ps
openshift/origin:v1.5.0
openshift/jenkins-2-centos7@sha256:2139bc280bb3717fbfd50e4f291afdec0b9822b40a3424d6ca137385731c4519

$ oc rsh jenkins-1-fq3cq 
sh-4.2$ grep openshift-sync /opt/openshift/base-plugins.txt
openshift-sync:0.1.20
```

**Comment by gabemontero** [comment]
thanks for the heads up @jwmullally 

quick heads up: normally we make changes in this repo and then push to github.com/jenkinsci/openshift-sync-plugin; but since we are a) trying to shut down 3.6, b) already have post-3.6 content in this repo (and no branch yet), I'll be checking in the fix / cutting the plugin release in github.com/jenkinsci/openshift-sync-plugin first, and then cherry-picking back to this repo

**Comment by gabemontero** [comment]
OK ... commit f12031b063ab8bf5e808dbf0229b4d43ab6cea3d is the fix for this issue in this repo

v0.1.22 is cooking in the jenkins update center .... I'll update / close this when the openshift jenkins centos images are updated with that version of the sync plugin

**Comment by jwmullally** [comment]
Thanks :)

**Comment by gabemontero** [comment]
yw :-) ... https://github.com/openshift/jenkins/pull/315 has merged ... new centos image will be up on docker hub within the hour ... closing out
