### ISSUE TITLE
openshift-sync-plugin does not work with IBM JDK

### ISSUE THREAD

**Issue by jerboaa** [openshift/jenkins-sync-plugin#179]
openshift-sync-plugin seems to be using an old version of okhttp3 which does not have this commit:
https://github.com/square/okhttp/commit/abc922206586bbeb026611b5c518c8e08ff90ed1

That commit/issue fixes a problem of using okhttp3 with IBM JDK. IBM's SSLSocket.getEnabledCipherSuites() returns ciphers different than OpenJDK. Ciphers are prefixed with `SSL_` rather than `TLS_`. Thus, comparison in `ConnectionSpec.isCompatible()` fails where it should actually succeed.

Example trace I'm getting is:

    Sep 26, 2017 1:45:46 PM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1 doRun
    SEVERE: Failed to load BuildConfigs: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
    io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
            at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:61)
            at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:52)
            at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:543)
            at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:68)
            at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.doRun(BuildConfigWatcher.java:82)
            at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:522)
            at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:319)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:191)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
            at java.lang.Thread.run(Thread.java:785)
    Caused by: java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_2], supportsTlsExtensions=true), ConnectionSpec()], supported protocols=[TLSv1.2]
            at okhttp3.internal.connection.ConnectionSpecSelector.configureSecureSocket(ConnectionSpecSelector.java:73)
            at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:234)
            at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
            at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
            at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
            at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
            at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
            at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at io.fabric8.openshift.client.internal.OpenShiftOAuthInterceptor.intercept(OpenShiftOAuthInterceptor.java:64)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
            at okhttp3.RealCall.execute(RealCall.java:60)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237)
            at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:232)
            at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:541)
            ... 10 more

I've used a byteman rule to work around this problem. With that rule in place which translates `TLS_`-prefixed ciphers to `SSL_`-prefixed ones the compatibility check passes and all is well.

**Comment by gabemontero** [comment]
discussed with @jerboaa offline, but the bumping of fabric8/okhttp is currently blocked by a regression in openshift/origin 3.6.0

@bparees and I have a to-do to sort out if we can, for the 3.6.x stream, claim we don't support 3.6.0 and require 3.6.x with the requisite commits

**Comment by gabemontero** [comment]
there is also the general issue of "official" IBM JDK toleration being tracked by https://trello.com/c/Gmc0sBIt/1393-jenkinsintegration-assess-openshift-jenkins-functionality-against-the-ibm-jdk

**Comment by gabemontero** [comment]
fabric client has been bumped;  between that and the referenced card above, which can capture any items in this space, closing out.
