### ISSUE TITLE
NPE on list ... also prevents watch registration ... no startegy jobs

### ISSUE THREAD

**Issue by gabemontero** [openshift/jenkins-sync-plugin#180]
Seen on https://api.ci.openshift.org jenkins 

```
SEVERE: Failed to load initial Builds: java.lang.NullPointerException
java.lang.NullPointerException
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$2.compare(BuildWatcher.java:164)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$2.compare(BuildWatcher.java:159)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:175)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher.onInitialBuilds(BuildWatcher.java:159)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:98)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

1) Builds in some sort of odd state (inspection of builds on system seemed OK though).

2) NPE prevents watch registration

3) jobs stay in new state

Jenkins job mgmt also blows up as a result

@stevekuznetsov @bparees

**Comment by gabemontero** [comment]
@stevekuznetsov - if possible, install this version of the sync plugin prior to any jenkins restart / clean up; it will address the build list npe, make sure the build watch is still registered if an error occurs on the list, and adds some additional debug

unzip it, and then from the jenkins ui go to the install plugins advanced tab and load the file in

thanks

[openshift-sync.zip](https://github.com/openshift/jenkins-sync-plugin/files/1396045/openshift-sync.zip)

**Comment by gabemontero** [comment]
in case it was not clear from earlier, if both list and watch are impacted, the plugin won't transition the build past new state

**Comment by gabemontero** [comment]
another clarification ... the sync plugin build list is for all new builds within a namespace, regardless of startegy ... we cannot scope the selector by strategy ... so a new build from any of the build configs in the origin-ci namespace could have been the one either missing annotations or missing the build number annotation (resulting in the NPE) ... unfortunately during debug with @stevekuznetsov I only focused on analyzing the pipeline strategy builds ... which for the builds which were not pruned when I started looking, all had valid annotations.

we of course filter for pipeline strategy after the builds have been received, but the NPE occurs before doing that

similarly, the build watch receives events for all builds in the namespace, and then has to filter ... but in this scenario, the watch registration was being prevented by the NPE

**Comment by gabemontero** [comment]
@csrwng @stevekuznetsov in case y'all were going to try my patch for this, but haven't actually gotten to it yet, here is an updated version (a couple of tweaks after more testing)

[openshift-sync.zip](https://github.com/openshift/jenkins-sync-plugin/files/1400045/openshift-sync.zip)
