### ISSUE TITLE
NullPointerException with arbitraryKeyValueTextCredential() potentially with Base64 decoding during SecretWatcher run

### ISSUE THREAD

**Issue by andyfeller** [openshift/jenkins-sync-plugin#262]
Picking up the most recent release of openshift-sync, we immediately ran into an issue where the new arbitrary secret logic throws NPE, however it's difficult to tell exactly where and why this is a problem as we have multiple projects being synced both with opaque secrets.
 
**openshift-sync version**: 1.0.28

**Stack trace:**
```
Sep 25, 2018 2:42:28 PM FINE io.fabric8.jenkins.openshiftsync.SecretWatcher$1 doRun
listing Secrets resources
Sep 25, 2018 2:42:28 PM SEVERE io.fabric8.jenkins.openshiftsync.SecretWatcher onInitialSecrets
Failed to update job
java.lang.NullPointerException
	at java.lang.String.<init>(String.java:515)
	at io.fabric8.jenkins.openshiftsync.CredentialsUtils.newSecretTextCredential(CredentialsUtils.java:286)
	at io.fabric8.jenkins.openshiftsync.CredentialsUtils.arbitraryKeyValueTextCredential(CredentialsUtils.java:211)
	at io.fabric8.jenkins.openshiftsync.CredentialsUtils.secretToCredentials(CredentialsUtils.java:250)
	at io.fabric8.jenkins.openshiftsync.CredentialsUtils.upsertCredential(CredentialsUtils.java:106)
	at io.fabric8.jenkins.openshiftsync.CredentialsUtils.upsertCredential(CredentialsUtils.java:97)
	at io.fabric8.jenkins.openshiftsync.SecretWatcher.upsertCredential(SecretWatcher.java:165)
	at io.fabric8.jenkins.openshiftsync.SecretWatcher.onInitialSecrets(SecretWatcher.java:122)
	at io.fabric8.jenkins.openshiftsync.SecretWatcher.access$100(SecretWatcher.java:37)
	at io.fabric8.jenkins.openshiftsync.SecretWatcher$1.doRun(SecretWatcher.java:69)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gabemontero** [comment]
thanks @andyfeller - I'll sort it out

I suppose you all have a ton of secrets and your not sure which one triggered this?

**Comment by andyfeller** [comment]
Yeah, we have 2 projects each with opaque secrets.  I **think** it maybe one that looks something like this:
```
apiVersion: v1
data:
  A: X##XXX==
  B: X##XXX==
  C: XXXXXXXXXXXXXXXXXX#XXXX#XXX=
  D: XXXXXXXXXX==
  E: XXXXXXX#XXXXXX==
  F: XXXXXXXXX#XX
  G: XXXXX#X#XXXXXXXXXXXXXX==
  H: XXXXXXXXXXXXXXXXXXXX
  I: XX##XXXXXXX#XXX#X#X#XX==
  J: XXXXXXXXXXXX
  K: XXXXXXXX
  L: XXXX
kind: Secret
metadata:
  labels:
    credential.sync.jenkins.openshift.io: 'true'
  name: super-secret
type: Opaque
```
But I can't be sure because there isn't any logging I can turn on for this 😞

**Comment by gabemontero** [comment]
Actually I'm thinking it could be blank/null data from an arbitrary point of view or one of the specific keys.  The existing impl is naive on that front.

Should have a PR relatively soon.  If trying out a pre-release version of the change is something you are willing to take on @andyfeller please let me know.

**Comment by gabemontero** [comment]
v1.0.29 of the sync plugin has been initiated with the JUC

**Comment by andyfeller** [comment]
Sorry for the delayed response @gabemontero.  I’d be happy to try out a pre-release!  Looking at the stacktrace, the only thing I can theorize is that the JSON transformation has something to do with it as all the secrets I’ve seen are not empty

**Comment by gabemontero** [comment]
No worries @andyfeller , but given the safety of the change, I went ahead and cut a new release, 1.0.29, which is now available at the update center.

And yep, if you see the PR, an issue with the JSON transformation was core to my thinking.

Give the new version a try at your convenience, and if it uncovers something additional that we can account for, we'll cut a new version, but at the least, I think we'll be at a place where secret data payload that we cannot deal with at least does not cause an NPE.

thanks

**Comment by gabemontero** [comment]
Oh, I can see about delaying an update to the openshift jenkins image, to pull in the new version of the plugin, for a bit if that gives you time to try it out.

**Comment by andyfeller** [comment]
thanks for the quick turnaround again!  I'm upgrading our plugin usage and seeing if it addresses the issue; will get back with you shortly.
