### ISSUE TITLE
jenkins flake in e2e-gcp-builds

### ISSUE THREAD

**Issue by gabemontero** [openshift/jenkins-sync-plugin#274]
```
 e2e-test-jenkins-pipeline-t45rm-openshift-jee-sample job log:
Creating placeholder flownodes because failed loading originals.
java.io.IOException: Tried to load head FlowNodes for execution Owner[e2e-test-jenkins-pipeline-t45rm/e2e-test-jenkins-pipeline-t45rm-openshift-jee-sample/2:e2e-test-jenkins-pipeline-t45rm/e2e-test-jenkins-pipeline-t45rm-openshift-jee-sample #2] but FlowNode was not found in storage for head id:FlowNodeId 1:7
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:678)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:715)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:875)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:745)
	at hudson.model.RunMap.retrieve(RunMap.java:225)
	at hudson.model.RunMap.retrieve(RunMap.java:57)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:499)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:481)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:379)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.search(AbstractLazyLoadRunMap.java:344)
	at jenkins.model.lazy.AbstractLazyLoadRunMap.newestBuild(AbstractLazyLoadRunMap.java:274)
	at jenkins.model.lazy.LazyLoadRunMapEntrySet$1.<init>(LazyLoadRunMapEntrySet.java:65)
	at jenkins.model.lazy.LazyLoadRunMapEntrySet.iterator(LazyLoadRunMapEntrySet.java:63)
	at java.util.AbstractMap$2$1.<init>(AbstractMap.java:411)
	at java.util.AbstractMap$2.iterator(AbstractMap.java:410)
	at hudson.util.RunList.iterator(RunList.java:113)
	at io.fabric8.jenkins.openshiftsync.JenkinsUtils.getRun(JenkinsUtils.java:476)
	at io.fabric8.jenkins.openshiftsync.JenkinsUtils.getRun(JenkinsUtils.java:470)
	at io.fabric8.jenkins.openshiftsync.JenkinsUtils.isAlreadyTriggered(JenkinsUtils.java:447)
	at io.fabric8.jenkins.openshiftsync.JenkinsUtils.triggerJob(JenkinsUtils.java:312)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher.flushBuildsWithNoBCList(BuildWatcher.java:380)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:197)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:190)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.eventReceived(BuildConfigWatcher.java:190)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.eventReceived(BuildConfigWatcher.java:235)
	at io.fabric8.jenkins.openshiftsync.WatcherCallback.eventReceived(WatcherCallback.java:34)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:237)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: ABORTED
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21558/pull-ci-openshift-origin-master-e2e-gcp-builds/162#openshift-tests-featurebuildsslow-openshift-pipeline-build-sync-plugin-tests-using-the-ephemeral-template-suiteopenshift

**Comment by gabemontero** [comment]
Could be related to https://github.com/openshift/jenkins-sync-plugin/pull/275

**Comment by gabemontero** [comment]
After some more digging I'm less inclined to think it is related to https://github.com/openshift/jenkins-sync-plugin/pull/275

Reading some of the more recent jenkins jiras (earlier this year) related to CpsFlowExecution.java, it looks like storage can be swapped out and things of this nature.

Also, that `Creating placeholder flownodes because failed loading originals.` was a bit of a clue.  Finding the source code for that, I found comments like 

```
/**
     * In the event we're missing FlowNodes, fail-fast and create some mockup FlowNodes so we can continue.
     * This avoids nulling out all of the execution's data
     * Bypasses {@link #croak(Throwable)} and {@link #onProgramEnd(Outcome)} to guarantee a clean path.
     */
```

All this is related to the resuming builds for various constraint reasons ...

I think the bottom line is that we have to put protection around the isAlreadyTriggered/getRun logic, and assume the job has not started if we get exceptions.  See what happens from there.

**Comment by gabemontero** [comment]
Tracking with https://bugzilla.redhat.com/show_bug.cgi?id=1657027
