### ISSUE TITLE
NPE on bluerun.getNodes().iterator() during upsert build - in jenkins master version=v3.11.82

### ISSUE THREAD

**Issue by clemensutschig** [openshift/jenkins-sync-plugin#286]
see https://github.com/opendevstack/ods-core/issues/86

on openshift 3.11 - latest 3.11 jenkins master & slaves

  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.upsertBuild(BuildSyncRunListener.java:336)
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.pollRun(BuildSyncRunListener.java:226)
  | at io.fabric8.jenkins.openshiftsync.BuildSyncRunListener.onFinalized(BuildSyncRunListener.java:193)
  | at hudson.model.listeners.RunListener.fireFinalized(RunListener.java:257)
  | at hudson.model.Run.onEndBuilding(Run.java:1998)
  | at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:611)
  | at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$900(WorkflowRun.java:132)
  | at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:993)
  | at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1440)
  | at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:417)
  | at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:35)
  | at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
  | at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
  | at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748) 

`Iterator<BluePipelineNode> iter = blueRun.getNodes().iterator();` is the NPE root ...

**Comment by clemensutschig** [comment]
BlueOcean 1.10.2 
· Core 2.150.2 
· 7b720c0 
· 16th January 2019 02:03 AM

also shows "Favoriting Error Organization undefined not found"

Jenkins ver. 2.150.2
