### ISSUE TITLE
Manual build does not start

### ISSUE THREAD

**Issue by isouza-daitan** [openshift/jenkins-sync-plugin#302]
Our manual builds started to intermittently fail to start after upgrading openshift-sync to 1.0.31. When the Build button is clicked, Jenkins goes to the main build interface and the job is not started.

I did some investigation and it appears to be caused by the changes in https://github.com/jenkinsci/openshift-sync-plugin/commit/50ea0b75c1fc44197b3599a766a3e92eb0d40861.

We have a proxy server that receives GitHub webhooks and triggers builds on Jenkins. This proxy injects some parameters that are not declared in the BuildConfig. The new code on `verifyEnvVars` does not like that and aborts the newly created build.

Another strange behavior is that although the Jenkins build is aborted, a new Openshift build is created with the default parameters (the ones set on the Jenkins UI are ignored). This Openshift build is eventually picked up by openshift-sync and a new Jenkins build is created with the default parameters.

These are the logs for a build that started correctly:
```
2019-04-16 21:18:13.481+0000 [id=27716] FINE    i.f.j.o.BuildDecisionHandler#dumpParams: param name PARAM_1 param value paramValue1
2019-04-16 21:18:13.481+0000 [id=27716] FINE    i.f.j.o.BuildDecisionHandler#dumpParams: param name PARAM_2 param value paramValue2
2019-04-16 21:18:13.482+0000 [id=27716] FINE    i.f.j.o.BuildDecisionHandler#dumpParams: param name PARAM_3 param value paramValue3
2019-04-16 21:18:13.482+0000 [id=27716] FINE    i.f.j.o.BuildDecisionHandler#dumpParams: param name PARAM_4 param value paramValue4
2019-04-16 21:18:13.482+0000 [id=27716] FINE    i.f.j.o.BuildDecisionHandler#dumpParams: param name PARAM_4 param value paramValue5
2019-04-16 21:18:13.482+0000 [id=27716] FINE    i.f.j.o.BuildDecisionHandler#shouldSchedule: ParametersAction: hudson.model.ParametersAction@74b8bd96
2019-04-16 21:18:13.482+0000 [id=27716] FINE    i.f.j.o.BuildDecisionHandler#dumpCause: cause: Started by user isouza
2019-04-16 21:18:13.482+0000 [id=27716] FINE    i.f.j.o.BuildDecisionHandler#shouldSchedule: get CauseAction: Cause
2019-04-16 21:18:13.482+0000 [id=27716] FINE    i.f.j.o.BuildDecisionHandler#shouldSchedule: Cause: Started by user isouza
2019-04-16 21:18:13.523+0000 [id=121]   INFO    i.f.j.o.BuildConfigWatcher$3#call: Updated job my-project-pull-request from BuildConfig NamespaceName{my-project:pull-request} with revision: 279635451
2019-04-16 21:18:13.535+0000 [id=213]   INFO    i.f.j.o.CredentialsUtils#upsertCredential: Updated credential my-project-github-access-token from Secret NamespaceName{my-project:github-access-token} 
with revision: 221276520
2019-04-16 21:18:13.539+0000 [id=213]   FINE    i.f.j.openshiftsync.JenkinsUtils#triggerJob: Adding existing causes...
2019-04-16 21:18:13.539+0000 [id=213]   FINE    i.f.j.openshiftsync.JenkinsUtils#triggerJob: orginal cause: Started by user isouza
2019-04-16 21:18:13.539+0000 [id=213]   FINE    i.f.j.openshiftsync.JenkinsUtils#triggerJob: new cause: OpenShift Build my-project/pull-request-3075 from https://github.com/myorg/my-project
2019-04-16 21:18:13.539+0000 [id=213]   FINE    i.f.j.openshiftsync.JenkinsUtils#triggerJob: new cause: Started by user isouza
2019-04-16 21:18:13.594+0000 [id=213]   FINE    i.f.j.openshiftsync.JenkinsUtils#triggerJob: setting job run params and since this is manually started from jenkins applying user provided parameters hudson.
model.ParametersAction@74b8bd96 along with any from bc's env vars
2019-04-16 21:18:13.595+0000 [id=213]   FINE    i.f.j.o.OpenShiftUtils#updateOpenShiftBuildPhase: setting build to Pending in namespace my-project/pull-request-3075
```

And these are the logs for an aborted build:
```
2019-04-16 21:18:43.599+0000 [id=28659] FINE    i.f.j.o.BuildDecisionHandler#dumpParams: param name PARAM_1 param value paramValue1
2019-04-16 21:18:43.599+0000 [id=28659] FINE    i.f.j.o.BuildDecisionHandler#dumpParams: param name PARAM_2 param value paramValue2
2019-04-16 21:18:43.599+0000 [id=28659] FINE    i.f.j.o.BuildDecisionHandler#dumpParams: param name PARAM_3 param value paramValue3
2019-04-16 21:18:43.599+0000 [id=28659] FINE    i.f.j.o.BuildDecisionHandler#dumpParams: param name PARAM_4 param value paramValue4
2019-04-16 21:18:43.599+0000 [id=28659] FINE    i.f.j.o.BuildDecisionHandler#dumpParams: param name PARAM_5 param value paramValue5
2019-04-16 21:18:43.599+0000 [id=28659] FINE    i.f.j.o.BuildDecisionHandler#shouldSchedule: ParametersAction: hudson.model.ParametersAction@b1d701f
2019-04-16 21:18:43.599+0000 [id=28659] FINE    i.f.j.o.BuildDecisionHandler#dumpCause: cause: Started by user isouza
2019-04-16 21:18:43.599+0000 [id=28659] FINE    i.f.j.o.BuildDecisionHandler#shouldSchedule: get CauseAction: Cause
2019-04-16 21:18:43.599+0000 [id=28659] FINE    i.f.j.o.BuildDecisionHandler#shouldSchedule: Cause: Started by user isouza
2019-04-16 21:18:43.674+0000 [id=121]   INFO    i.f.j.o.BuildConfigWatcher$3#call: Updated job my-project-pull-request from BuildConfig NamespaceName{my-project:pull-request} with revision: 279635660
2019-04-16 21:18:46.050+0000 [id=213]   INFO    i.f.j.o.CredentialsUtils#upsertCredential: Updated credential my-project-github-access-token from Secret NamespaceName{my-project2:github-access-token} with revision: 221276520
2019-04-16 21:18:46.054+0000 [id=213]   FINE    i.f.j.openshiftsync.JenkinsUtils#triggerJob: Adding existing causes...
2019-04-16 21:18:46.054+0000 [id=213]   FINE    i.f.j.openshiftsync.JenkinsUtils#triggerJob: orginal cause: Started by user isouza
2019-04-16 21:18:46.054+0000 [id=213]   FINE    i.f.j.openshiftsync.JenkinsUtils#triggerJob: new cause: OpenShift Build my-project/pull-request-3077 from https://github.com/myorg/my-project
2019-04-16 21:18:46.054+0000 [id=213]   FINE    i.f.j.openshiftsync.JenkinsUtils#triggerJob: new cause: Started by user isouza
2019-04-16 21:18:46.100+0000 [id=213]   WARNING i.f.j.openshiftsync.BuildWatcher#eventReceived: Caught: hudson.AbortException: A run of workflow job my-project-pull-request was expecting parameter PARAM_SET_BY_PROXY, but it is not in the parameter list
hudson.AbortException: A run of workflow job my-project-pull-request was expecting parameter PARAM_SET_BY_PROXY, but it is not in the parameter list
        at io.fabric8.jenkins.openshiftsync.JenkinsUtils$1.call(JenkinsUtils.java:198)
        at io.fabric8.jenkins.openshiftsync.JenkinsUtils$1.call(JenkinsUtils.java:148)
        at hudson.security.ACL.impersonate(ACL.java:290)
        at io.fabric8.jenkins.openshiftsync.JenkinsUtils.verifyEnvVars(JenkinsUtils.java:148)
        at io.fabric8.jenkins.openshiftsync.JenkinsUtils.triggerJob(JenkinsUtils.java:479)
        at io.fabric8.jenkins.openshiftsync.BuildWatcher.addEventToJenkinsJobRun(BuildWatcher.java:345)
        at io.fabric8.jenkins.openshiftsync.BuildWatcher.eventReceived(BuildWatcher.java:165)
        at io.fabric8.jenkins.openshiftsync.BuildWatcher.eventReceived(BuildWatcher.java:187)
        at io.fabric8.jenkins.openshiftsync.WatcherCallback.eventReceived(WatcherCallback.java:34)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:237)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Is this behavior intentional? If yes, why does it happen intermittently? Should this change be noted as backwards incompatible in the release notes?

Additionally, do you have any suggested solutions besides adding the extra parameters to the BuildConfig?

**Comment by gabemontero** [comment]
hi @isouza-daitan  .... thanks for the research into our commits wrt abort exception you see.  It expedited things.

Yeah, the commit you noted was a nasty, intermittent problem we tackled in Nov 2018.  If you are interested in some of the gory details, follow some of the contents in the original PR in https://github.com/openshift/jenkins-sync-plugin ... like https://github.com/openshift/jenkins-sync-plugin/pull/273#issuecomment-438373779 for example.  In the corresponding issue, see https://github.com/openshift/jenkins-sync-plugin/issues/272#issuecomment-437981962 for example.

Given that experience, I would be surprised if you did NOT see intermittent behaviour.

With that context, the exception you see is thrown when we 
a) attempted to update the params in the job based on the dynamic envs added (in your case, the envs the proxy injected), including saving the job
b) did not see that change reflected we we attempted to read the job from jenkins persisted store for up to 5 seconds

If the job has not been successfully update with the dynamic params/envs when we attempt to process the build, we then see errors like those noted in https://github.com/openshift/jenkins-sync-plugin/issues/272

Adding the complete set of possible envs/params into the BC is the only truly assured thing to bypass this intermittent "jenkins may be overloaded behavior" wrt our bc/build env to job param mapping.

And sure, I could see adding this recommendation either in this plugin's readme or the associated openshift doc at https://docs.okd.io/latest/dev_guide/builds/build_strategies.html#jenkins-pipeline-strategy-environment

We will use this issue to drive that.  

thanks

@pradeepto @sthaha @waveywaves fyi

**Comment by isouza-daitan** [comment]
@gabemontero thanks for the detailed response.
