### ISSUE TITLE
Plugin stops working with NPE wrt Namespaces in Openshift 4.x

### ISSUE THREAD

**Issue by waveywaves** [openshift/jenkins-sync-plugin#326]
### Description

Shortly after Jenkins starts with jenkins-sync-plugin installed on Openshift 4.x where the corresponding version of kubernetes-client is being leveraged by the sync-plugin, the following errors can be seen.

1> The first one which we get is a `java.lang.NoSuchMethodError` error, which states that there is no method called io.fabric8.openshift.client.OpenShiftConfig.isDisableHostnameVerification()Z present. After checking in https://github.com/fabric8io/kubernetes-client/blob/master/openshift-client/src/main/java/io/fabric8/openshift/client/OpenShiftConfig.java , it is clear that the method is not present where it was expected by the sync plugin to be.

```
INFO: Started all plugins                                                                                                                                                                                 [40/3007]
Aug 07, 2019 4:01:37 AM io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration configChange
INFO: OpenShift Sync Plugin processing a newly supplied configuration
Aug 07, 2019 4:01:37 AM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate Key[type=io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration, annotation=[none]]; skipping this component                                                                   
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: io.fabric8.openshift.client.OpenShiftConfig.isDisableHostnameVerification()Z                                                                         
  at io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration.<init>(GlobalPluginConfiguration.java:100)                                                                                                        

1 error
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)                                                                                              
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
        at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:439)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)                                                                                              
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:401)
        at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:392)
        at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:339)
        at hudson.ExtensionList.load(ExtensionList.java:381)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
        at hudson.ExtensionList.getComponents(ExtensionList.java:183)
        at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:193)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
        at hudson.ExtensionList.iterator(ExtensionList.java:172)
        at jenkins.branch.CustomOrganizationFolderDescriptor.doAddSpecificDescriptors(CustomOrganizationFolderDescriptor.java:166)                                                                                
        at jenkins.branch.CustomOrganizationFolderDescriptor.addSpecificDescriptors(CustomOrganizationFolderDescriptor.java:145)                                                                                  
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1095)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: io.fabric8.openshift.client.OpenShiftConfig.isDisableHostnameVerification()Z                                                                                              
        at io.fabric8.openshift.client.OpenShiftConfigBuilder.<init>(OpenShiftConfigBuilder.java:94)
        at io.fabric8.openshift.client.OpenShiftConfigBuilder.<init>(OpenShiftConfigBuilder.java:16)
        at io.fabric8.openshift.client.OpenShiftConfigBuilder.<init>(OpenShiftConfigBuilder.java:13)
        at io.fabric8.jenkins.openshiftsync.OpenShiftUtils.initializeOpenShiftClient(OpenShiftUtils.java:133)                                                                                                     
        at io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration.configChange(GlobalPluginConfiguration.java:277)                                                                                            
        at io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration.<init>(GlobalPluginConfiguration.java:102)                                                                                                  
        at io.fabric8.jenkins.openshiftsync.GlobalPluginConfiguration$$FastClassByGuice$$7bc306ea.newInstance(<generated>)                                                                                        
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)                                                                                      
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)                                                                                 
        at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:566)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)                                                                                 
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)                                                                                            
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)                                                                                           
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)                                                                                              
        ... 30 more

```

2> Here there is an NPE taking place during the initialization of the PipelineJobListener at https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/PipelineJobListener.java#L82 . Where the `getOpenshiftClient()` and `namespace` are `null` after troubleshooting. After a little digging through seems to be an issue wrt https://github.com/openshift/jenkins-sync-plugin/blob/master/src/main/java/io/fabric8/jenkins/openshiftsync/OpenShiftUtils.java#L148-L164

```
Aug 07, 2019 4:01:40 AM hudson.util.Retrier start                                                                                                                                                                 
INFO: Attempt #1 to do the action check updates server                                                                                                                                                            
Aug 07, 2019 4:01:40 AM jenkins.InitReactorRunner$1 onAttained                                                                                                                                                    
INFO: Completed initialization                                                                                                                                                                                    
Aug 07, 2019 4:01:40 AM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate Key[type=io.fabric8.jenkins.openshiftsync.PipelineJobListener, annotation=[none]]; skipping this component                                                                         
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NullPointerException
  at io.fabric8.jenkins.openshiftsync.PipelineJobListener.<init>(PipelineJobListener.java:61)

1 error
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)                                                                                              
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
        at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:439)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)                                                                                              
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:401)
        at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:392)
        at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:339)
        at hudson.ExtensionList.load(ExtensionList.java:381)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:317)
        at hudson.ExtensionList.iterator(ExtensionList.java:172)
        at jenkins.model.Jenkins.<init>(Jenkins.java:996)
        at hudson.model.Hudson.<init>(Hudson.java:85)
        at hudson.model.Hudson.<init>(Hudson.java:81)
        at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused by: java.lang.NullPointerException
        at io.fabric8.jenkins.openshiftsync.OpenShiftUtils.getNamespaceOrUseDefault(OpenShiftUtils.java:373)                                                                                                      
        at io.fabric8.jenkins.openshiftsync.PipelineJobListener.init(PipelineJobListener.java:90)
        at io.fabric8.jenkins.openshiftsync.PipelineJobListener.<init>(PipelineJobListener.java:62)
        at io.fabric8.jenkins.openshiftsync.PipelineJobListener$$FastClassByGuice$$ff6b8e19.newInstance(<generated>)                                                                                              
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)                                                                                      
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
        at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:89)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)                                                                                 
        at hudson.ExtensionFinder$GuiceFinder$SezpozModule.onProvision(ExtensionFinder.java:566)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:126)                                                                                 
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:68)                                                                                            
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:87)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)   
```

cc @akram

**Comment by waveywaves** [comment]
I have a fix in mind for this. Will raise a PR in the meantime.

**Comment by waveywaves** [comment]
This mostly seems like an edge case scenario. As I deployed another jenkins instance in a 4.2 cluster and tested it out with the same version of sync plugin as last time i.e. 1.0.41-SNAPSHOT.

Let's keep this on a watch in the meantime.

**Comment by waveywaves** [comment]
Closed with info in #327

**Comment by lionelve** [comment]
Hi @waveywaves, do these fixes make it into the upstream plugin at https://github.com/jenkinsci/openshift-sync-plugin ?

**Comment by waveywaves** [comment]
@lionelve Yes they do

**Comment by YevheniiPokhvalii** [comment]
The same error on OpenShift Sync Version 1.0.55

**Comment by MichaelIshri** [comment]
We're getting it too on OpenShift 4 as well. It doesn't seem to affect anything though. Maybe we're not using the feature this is intended for?

**Comment by coreydaley** [comment]
> We're getting it too on OpenShift 4 as well. It doesn't seem to affect anything though. Maybe we're not using the feature this is intended for?

We have a series of pull requests open to the various repos that we are testing and hope to have merged and released soon that should fix all of this nonsense.
