### ISSUE TITLE
Openshift Sync 1.0.42 breaks credentials synchronization (Openshift 3.9 - Jenkins 2.190.1)

### ISSUE THREAD

**Issue by jdcano-bpe** [openshift/jenkins-sync-plugin#355]
Hello,

Thanks for the great job you are doing.

I have a Jenkins 2.190.1 with the Openshift integration (version 3.9) and all works perfectly except the last upgrade of the OpenShift Sync 1.0.42. After the installation, Jenkins is not able to find the credentials anymore and then we can not fetch, build or access to the cluster anymore.

Would you need more information or replication? With the 1.0.41 all is working perfectly.

Thanks a lot in advance.

**Comment by akram** [comment]
Hi @jdcano-bpe ,

thank you for reporting this issue. Indeed, if you have more informations, we are interested!
For which kind of credentials are you seing malfunction of synchronisation?


cc @waveywaves

**Comment by jdcano-bpe** [comment]
Hello @akram 

Thanks for your message.
We are having this problem with SSH credentials.

Just to clarify, I know that the problem is related or the plugin is involved in this issue because is the only one that is not updated, and when I update it the access to the credentials are broken. Once I downgrade all is working fine again.

The versions of the Git plugins are:
- Git Server 1.8
- Git client 2.9.0
- Git plugin 3.12.1

Our GIT server is Bitbucket (version 6.7.1), but it has been happening with previous versions as well.

When I try to connect to a repository to build something or fetch tags from any repository in Jenkins, I got this error after the upgrade:

```
[ cicd/cicd-ms-myrepo-dev-pipeline ]  Download tags from the repository failed
hudson.plugins.git.GitException: Command "git ls-remote -t ssh://git@bitbucket-server.cicd.svc.cluster.local:7999/wor/myrepo.git *" returned status code 128:
stdout: 
stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2174)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1866)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1771)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1762)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.getRemoteReferences(CliGitAPIImpl.java:3013)
	at net.uaznia.lukanus.hudson.plugins.gitparameter.GitParameterDefinition.getTag(GitParameterDefinition.java:352)
	at net.uaznia.lukanus.hudson.plugins.gitparameter.GitParameterDefinition.generateContents(GitParameterDefinition.java:292)
	at net.uaznia.lukanus.hudson.plugins.gitparameter.GitParameterDefinition$DescriptorImpl.doFillValueItems(GitParameterDefinition.java:618)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at **org.openshift.jenkins.plugins.openshiftlogin.OpenShiftPermissionFilter.doFilter(OpenShiftPermissionFilter.java:247)**
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:246)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```
In the Openshift logs I could not found any reference or error, and in Bitbucket I got only the 403 because we are not presenting the ssh keys anymore.

Thanks a lot.

Best regards,

**Comment by akram** [comment]
@jdcano-bpe can you check if you are not facing this issue: https://github.com/openshift/jenkins-sync-plugin/issues/345 ?

We have been reported an issue with SSH credentials synchronisation not operated properly. If you try to edit and then save (without any change) the ssh credential, does it workaround the issue?

**Comment by jdcano-bpe** [comment]
Hello, 

Thanks for your quick answer. I actually did it, I just edit, add the usual SSH credential and save. But I still get the same error:

```
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from ssh://git@bitbucket-server.cicd.svc.cluster.local:7999/wor/ms-myrepo.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:894)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1161)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1192)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:124)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:149)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:67)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:299)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress ssh://git@bitbucket-server.cicd.svc.cluster.local:7999/wor/ms-myrepo.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2174)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1866)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:78)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:547)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:892)
	... 8 more
ERROR: Error fetching remote repo 'origin'
ERROR: Maximum checkout retry attempts reached, aborting
Finished: FAILURE
```
And with the scripts (groovy) to access to some repository I have the same error.

Thanks again.
Best regards,

**Comment by akram** [comment]
Hi @jdcano-bpe ,

I tried with 1.0.42 and 1.0.43-SNAPSHOT of the sync plugin and I can't reproduce it.
Do you have the ability to try with 2.176.3 version of Jenkins ?


Also, here is a comment I put on another bug when I tried to reproduce what you are saying.
Can you try to reproduce also using this, even on 2.190 ?


I tried to reproduce the issue with no success by using a simple git checkout which uses an SSH private key to checkout a private repo on git hub GitHub .

I am using the version 1.0.41 of the sync plugin on an openshift 4.2 server.

Here is the test pipeline that I am using:
https://github.com/akram/pipes/blob/jenkins-sync-plugin-issue-345/Jenkinsfile

replace the private repo with your own. (github.com:akram/private-pipes.git)
it also works with public repo by the way.

You can instantiate this pipeline with:

```
oc new-project my-project
oc new-app jenkins-persistent
oc new-build https://github.com/akram/pipes#jenkins-sync-plugin-issue-345
oc create secret generic my-private-ssh-key --from-file=ssh-privatekey=$HOME/.ssh/id_rsa --from-literal=username=akram
oc label secret my-private-ssh-key  credential.sync.jenkins.openshift.io=true
```

**Comment by jdcano-bpe** [comment]
Hello @akram 

Sorry for my late answer. Answering to your questions:

- In our previous Jenkins installation, we were using the version 2.176.2 and 2.176.3 and in both cases I was having the same issue.
- I tried your Jenkinsfile and it does not works in our cluster.

But after some other tests, I think I found the problem:

- In my case, the SSH credentials in Openshift were created as **kubernetes.io/ssh-auth** type with the name **cicd-openshift-ssh**. 
- If I follow your instructions, the SSH credentials in Openshift are created as **Opaque** with the name **cicd-openshift-ssh**.

After running few tests and your recommendation, in my case I found out the following:

-  The version 1.0.41 synchronizes the SSH credential from Openshift to Jenkins in a **SSH Username with private key** Jenkins credential type. ![ssh_username_key_jenkins](https://user-images.githubusercontent.com/49392580/68200544-6aac6f00-ffc0-11e9-9814-ea336f96a20b.png)

- The version 1.0.42 looks for a **Secret text** with the name  **cicd-openshift-ssh** and does not find any **Secret text** with that name, because in my case I have **SSH Username with private key**

- If I delete in Openshift and Jenkins the **SSH Username with private key** and I recreate it using your recommendation it is created as a **Secret text** in Jenkins and then the job can not find the credential anymore even if they have the same name.  I did a small research and apparently Jenkins does not allow to use **Secret text** for Git credentials in a SCM Pipeline job, and after recreating the SSH credential as **Secret text**, this stopped appearing in the credentials options in the Jenkins Pipeline job, but in the case of the **SSH Username with private key**  it stills appears and is selected automatically.  ![credentials_jenkins](https://user-images.githubusercontent.com/49392580/68199879-1d7bcd80-ffbf-11e9-807f-9589906756b0.png)

So, I think, I will have to modify my Jenkinsfile to take the credentials from there or just keep using this version for a while... Do you think I have any other option or I am missing something?

Thanks a lot again.
Best regards,

**Comment by akram** [comment]
@jdcano-bpe , ok, that gives more insights

Can you explain me this: 

> The version 1.0.42 looks for a Secret text with the name cicd-openshift-ssh and does not find any Secret text with that name, because in my case I have SSH Username with private key 

Also, you must notice that we automatically prefix the credential id with the project/namespace name. (unless you specify it through an annotation on the secret).

So, if you "follow my instructions" , then you should have found a credential in Jenkins named `<your-project>-cicd-openshift-ssh`

**Comment by jdcano-bpe** [comment]
Thanks a lot for your answer.

>  Can you explain me this:
> 
> The version 1.0.42 looks for a Secret text with the name cicd-openshift-ssh and does not find any Secret text with that name, because in my case I have SSH Username with private key

From the tests I did in my environment, I came to that conclusion, because of the following:

- With the version 1.0.41 installed in Jenkins:
  - In my project (CICD), I created a key of type **kubernetes.io/ssh-auth** named **openshift-ssh**.
  - In Jenkins, in the credentials area, a new credential of type **SSH Username with private key** named **cicd-openshift-ssh** is generated automatically by the plugin.
  - That type of credential is valid to be used in a Pipeline Job, so all is working fine.

- Doing the same test with the version 1.0.42 installed in Jenkins:
  - Without changing any configuration, upgrade the plugin from the version 1.0.41 to the version 1.0.42.
  - The plugin removes the credential from the Openshift Pipeline Job in Jenkins, furthermore, the Job fails because can not access to the SCM GIT repository. Everytime I set the existing credential named **cicd-openshift-ssh**, it is automatically removed after saving the job configuration.
  - Then I performed the following tests:
    - If in my Openshift project **CICD**, I remove the SSH key named **openshift-ssh**. 
    - I create a new key (following your instructions). This generates a new credential of type **Opaque** named **openshift-ssh**.
    - The key is synchronized into Jenkins, and a new credential named **cicd-openshift-ssh** of type **Secret text** appears in the Jenkins's credentials section.
    - I can not use that credential in my Openshift Pipeline Job in Jenkins cause is not available in the list of available credentials to access to the SCM repository.

So as conclusion, in the version 1.0.42, I came to think that the plugin is trying to use the credential named **cicd-openshift-ssh**, but it is looking for a **Secret text** credential type and it is just finding a credential type **SSH Username with private key** even if they have the very same name **cicd-openshift-ssh** in the Jenkins credentials store.

Actually, searching a bite more in detail, this is what is happening to me (**Secret Text** is not supported by the Git Plugin):

https://issues.jenkins-ci.org/browse/JENKINS-40009

Hope is more clear now. The only workaround to be able to use the latest version of the Synch plugin, is to use a HTTPS instead of a SSH for cloning the repository.

Do you think there is any other workaround? Could the Openshift Sync plugin generate another type of credential, instead of **Secret text**?

Thanks a lot again.
Best regards.

**Comment by akram** [comment]
hi @jdcano-bpe 

we have just released the 1.0.43 version which contains the fix for this one. Can you try it and confirm that it fixes your issue ?
thanks

**Comment by jdcano-bpe** [comment]
Hello @akram ,

I updated to the 1.0.43 version. I ran the very same tests and we tested in our office working with this new version and all works fine and as expected. So, no errors and all is working fine!

Thanks a lot for your great job!!
Best regards,

**Comment by akram** [comment]
good news , kudos to @waveywaves for the good catch
