### ISSUE TITLE
Credentials randomly reseted, causing pipeline outages

### ISSUE THREAD

**Issue by instagendleg** [openshift/jenkins-sync-plugin#384]
### Versions

```
Kubernetes Cluster Version: v1.18.3+fa69cae
OpenShift Sync: 1.0.46
OpenShift Client Jenkins Plugin: 1.0.34
Jenkins: 2.263.4
Kubernetes Client API Plugin: 4.13.2-1
Kubernetes Credentials Plugin: 0.8.0
Kubernetes plugin: 1.29.2
```

### Debug Output

```
2021-03-04 17:11:08.622+0000 [id=26]	INFO	i.f.j.openshiftsync.BuildWatcher#reconcileRunsAndBuilds: Reconciling job runs and builds
2021-03-04 17:13:53.698+0000 [id=65]	INFO	i.f.j.o.SecretWatcher#modifyCredential: Modifying Secret with Uid xxx with Name token-aws-jenkins-eu-default-cicd
2021-03-04 17:13:53.698+0000 [id=65]	INFO	i.f.j.o.SecretWatcher#validSecret: Validating Secret with Uid xxx with Name token-aws-jenkins-eu-default-cicd
2021-03-04 17:13:53.702+0000 [id=65]	INFO	i.f.j.o.CredentialsUtils#upsertCredential: Created credential xxx-token-aws-jenkins-eu-default-cicd from Secret NamespaceName{xxx:token-aws-jenkins-eu-default-cicd} with revision: 930167478
2021-03-04 17:16:07.615+0000 [id=41]	SEVERE	i.f.j.o.BuildConfigWatcher$1#doRun: Failed to load BuildConfigs: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/build.openshift.io/v1/namespaces/xxx/buildconfigs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. buildconfigs.build.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot list resource "buildconfigs" in API group "build.openshift.io" in the namespace "xxx".
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/build.openshift.io/v1/namespaces/xxx/buildconfigs. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. buildconfigs.build.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot list resource "buildconfigs" in API group "build.openshift.io" in the namespace "xxx".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:418)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:160)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:675)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:84)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.doRun(BuildConfigWatcher.java:105)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 17:16:07.615+0000 [id=41]	WARNING	i.f.j.o.BuildConfigWatcher$1#doRun: Unable to get build config list; impacts resource version used for watch
2021-03-04 17:16:07.615+0000 [id=35]	SEVERE	i.f.j.o.BuildWatcher$1#doRun: Failed to load initial Builds: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/build.openshift.io/v1/namespaces/xxx/builds?fieldSelector=status%3DNew. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. builds.build.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot list resource "builds" in API group "build.openshift.io" in the namespace "xxx".
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/build.openshift.io/v1/namespaces/xxx/builds?fieldSelector=status%3DNew. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. builds.build.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot list resource "builds" in API group "build.openshift.io" in the namespace "xxx".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:418)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:160)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:675)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:84)
	at io.fabric8.jenkins.openshiftsync.BuildWatcher$1.doRun(BuildWatcher.java:113)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 17:16:07.616+0000 [id=35]	WARNING	i.f.j.o.BuildWatcher$1#doRun: Unable to get build list; impacts resource version used for watch
2021-03-04 17:16:07.616+0000 [id=35]	INFO	i.f.j.o.BuildWatcher$1#doRun: creating Build watch for namespace xxx and resource version 0
2021-03-04 17:16:07.615+0000 [id=41]	INFO	i.f.j.o.BuildConfigWatcher$1#doRun: creating BuildConfig watch for namespace xxx and resource version 0
2021-03-04 17:16:07.616+0000 [id=39]	SEVERE	i.f.j.o.ImageStreamWatcher$1#doRun: Failed to load ImageStreams: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/image.openshift.io/v1/namespaces/xxx/imagestreams. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. imagestreams.image.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot list resource "imagestreams" in API group "image.openshift.io" in the namespace "xxx".
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/image.openshift.io/v1/namespaces/xxx/imagestreams. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. imagestreams.image.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot list resource "imagestreams" in API group "image.openshift.io" in the namespace "xxx".
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:570)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:474)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:435)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:418)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:160)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:675)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:84)
	at io.fabric8.jenkins.openshiftsync.ImageStreamWatcher$1.doRun(ImageStreamWatcher.java:58)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 17:16:07.616+0000 [id=39]	WARNING	i.f.j.o.ImageStreamWatcher$1#doRun: Unable to get image stream list; impacts resource version used for watch
2021-03-04 17:16:07.616+0000 [id=39]	INFO	i.f.j.o.ImageStreamWatcher$1#doRun: creating ImageStream watch for namespace xxx and resource version 0
2021-03-04 17:16:07.618+0000 [id=20347]	WARNING	i.f.k.c.d.i.WatchConnectionManager$1#onFailure: Exec Failure: HTTP 403, Status: 403 - imagestreams.image.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot watch resource "imagestreams" in API group "image.openshift.io" in the namespace "xxx"
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 17:16:07.618+0000 [id=39]	INFO	i.f.j.openshiftsync.BaseWatcher#onClose: Watch for type io.fabric8.jenkins.openshiftsync.ImageStreamWatcher closed for one of the following namespaces: []
2021-03-04 17:16:07.619+0000 [id=20346]	WARNING	i.f.k.c.d.i.WatchConnectionManager$1#onFailure: Exec Failure: HTTP 403, Status: 403 - buildconfigs.build.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot watch resource "buildconfigs" in API group "build.openshift.io" in the namespace "xxx"
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 17:16:07.619+0000 [id=41]	INFO	i.f.j.openshiftsync.BaseWatcher#onClose: Watch for type io.fabric8.jenkins.openshiftsync.BuildConfigWatcher closed for one of the following namespaces: []
2021-03-04 17:16:07.620+0000 [id=20345]	WARNING	i.f.k.c.d.i.WatchConnectionManager$1#onFailure: Exec Failure: HTTP 403, Status: 403 - builds.build.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot watch resource "builds" in API group "build.openshift.io" in the namespace "xxx"
java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:229)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 17:16:07.621+0000 [id=35]	INFO	i.f.j.openshiftsync.BaseWatcher#onClose: Watch for type io.fabric8.jenkins.openshiftsync.BuildWatcher closed for one of the following namespaces: []
2021-03-04 17:16:07.621+0000 [id=41]	SEVERE	i.f.j.o.BuildConfigWatcher$1#doRun: Failed to load BuildConfigs: io.fabric8.kubernetes.client.KubernetesClientException: buildconfigs.build.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot watch resource "buildconfigs" in API group "build.openshift.io" in the namespace "xxx"
Also:   java.lang.Throwable: waiting here
		at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:154)
		at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:341)
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:820)
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:793)
		at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:84)
		at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$1.doRun(BuildConfigWatcher.java:120)
		at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
		at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
io.fabric8.kubernetes.client.KubernetesClientException: buildconfigs.build.openshift.io is forbidden: User "system:serviceaccount:xxx:jenkins" cannot watch resource "buildconfigs" in API group "build.openshift.io" in the namespace "xxx"
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:202)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-03-04 17:16:07.666+0000 [id=46]	INFO	i.f.j.o.SecretWatcher#validSecret: Validating Secret with Uid xxx with Name token-artifactory-jenkins
[...]
2021-03-04 17:16:08.619+0000 [id=39]	WARNING	i.f.k.c.d.i.WatchConnectionManager#close: Executor didn't terminate in time after shutdown in close(), killing it in: io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@4a563bcc
```

### Crash Output

```
2021-03-04 17:16:08.619+0000 [id=39]	WARNING	i.f.k.c.d.i.WatchConnectionManager#close: Executor didn't terminate in time after shutdown in close(), killing it in: io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@4a563bcc
```

### Expected Behavior

My credentials are tagged with `credential.sync.jenkins.openshift.io=true`, these are available a few seconds later in my Jenkins pipelines.

### Actual Behavior

Randomly (from my end-user perception), the credentials are wiped. Then, these come back randomly to be fully re-sync 30 minutes later.

### Steps to Reproduce

* Install Jenkins on OpenShift
* Sync some credentials
* Wait

### Additional Context

* I proactively denied the permission to access to `buildconfigs.build.openshift.io` and `imagestreams.image.openshift.io` because I didn't want to use these features.

### References

n/a

**Comment by akram** [comment]
thank you @instagendleg  for reporting this. 
Could you please tell me also which version of OpenShift / kubernetes you are using?
And, do you see any `timeout` related error message in your logs prior to this erro?

**Comment by instagendleg** [comment]
Hi @akram, here is:

```
Kubernetes Cluster Version: v1.18.3+fa69cae
OpenShift Cluster Version: 4.5
```

**Comment by instagendleg** [comment]
I also confirm there is no timeout during the 1-hour timeframe preceding the issue.

**Comment by akram** [comment]
ok, re-reading your issue, I just seen that:

> I proactively denied the permission to access to buildconfigs.build.openshift.io and imagestreams.image.openshift.io because I didn't want to use these features.

so, the 403 error code for buildconfig is expected, but is an issue is that, as a side effect your credentials got deleted and then recreated? Is that what you are telling?

I was checking if there was any global connection resets on the plugin side, but we don't have such a thing. IIRC, there is a caching mechanism in the `kubernetes-client` library that we us. I have to check there.

**Comment by instagendleg** [comment]
> so, the 403 error code for buildconfig is expected, but is an issue is that, as a side effect your credentials got deleted and then recreated? Is that what you are telling?

That's right. I except 403 errors from the plugin because I denied images & builds access permissions. And multiple times per day, all my Jenkins synchronized credentials are deleted then created progressively during the next 30 minutes.

**Comment by instagendleg** [comment]
I got new debugging information. Now, my Jenkins instance is facing the same issue. I tested multiple credentials and in all cases, I see (I took the same credentials for the example, to match the credentials UUID):

```
2021-03-05 13:36:41.162+0000 [id=41]	INFO	i.f.j.o.SecretWatcher#validSecret: Validating Secret with Uid 65553d96-5a0b-4f90-92bf-d29c52502db9 with Name [credential-name]
2021-03-05 13:36:41.162+0000 [id=41]	INFO	i.f.j.o.SecretWatcher#upsertCredential: Upserting Secret with Uid 65553d96-5a0b-4f90-92bf-d29c52502db9 with Name [credential-name]
2021-03-05 13:36:41.162+0000 [id=41]	INFO	i.f.j.o.SecretWatcher#validSecret: Validating Secret with Uid 65553d96-5a0b-4f90-92bf-d29c52502db9 with Name [credential-name]
2021-03-05 13:36:41.175+0000 [id=41]	INFO	i.f.j.o.CredentialsUtils#upsertCredential: Created credential [k8s-namespace]-[credential-name] from Secret NamespaceName{[k8s-namespace]:[credential-name]} with revision: 906033430
```

Then, repeating every 5 seconds, with no errors surrounding:

```
2021-03-08 16:41:39.631+0000 [id=47]	INFO	i.f.j.o.SecretWatcher#validSecret: Validating Secret with Uid 65553d96-5a0b-4f90-92bf-d29c52502db9 with Name [credential-name]
```

I confirm that the credentials are not available from any pipeline neither in https://[jenkins-root]/credentials/.

**Comment by instagendleg** [comment]
Not fixed.

/remove-lifecycle stale

**Comment by akram** [comment]
@instagendleg we have released 1.0.47 and 1.0.48 which contains now a configuration parameter to disable sync on a per type basis. So, you can disable `BuildConfig` and  `ImageStream` syncing without removing the permissions on them.

Can you test one of these versions and tell me if you still see the issue with credentials not properly syncing when the jenkins ServiceAccount has its default permissions?

**Comment by trash-80** [comment]
This issue matches the issue I put in 392
The latest update fails to init sync, then after a while, starts deleting credentials and sync'd Jenkins Agents.
