### ISSUE TITLE
no RBAC policy matched

### ISSUE THREAD

**Issue by candalmartin** [openshift/jenkins-sync-plugin#387]
After upgrading the openshift-sync plugint from 1.0.45 to 1.0.46, the synchronyzartions started to fail with this error:

Failed to load ConfigMaps: io.fabric8.kubernetes.client.KubernetesClientException: configmaps is forbidden: User "system:anonymous" cannot watch configmaps in the namespace "my_test_namespace": no RBAC policy matched
Also:   java.lang.Throwable: waiting here
	at io.fabric8.kubernetes.client.utils.Utils.waitUntilReady(Utils.java:154)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.waitUntilReady(WatchConnectionManager.java:341)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:820)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:793)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.watch(BaseOperation.java:84)
	at io.fabric8.jenkins.openshiftsync.ConfigMapWatcher$1.doRun(ConfigMapWatcher.java:82)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
io.fabric8.kubernetes.client.KubernetesClientException: configmaps is forbidden: User "system:anonymous" cannot watch configmaps in the namespace "almt-test-dev": no RBAC policy matched
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onFailure(WatchConnectionManager.java:202)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:198)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I don't know why is using "system:anonymous" as service account, because I configured other SA.

**My environment:**
Openshift 3.11.404
Kubernetes v1.11.0+d4cacc0
Jenkins 2.277.4.3
OpenShift Sync Plugin 1.0.46
OpenShift Client Jenkins Plugin 1.0.34
Kubernetes plugin 1.29.2
Kubernetes Credentials Plugin 0.8.0
Kubernetes Client API Plugin 4.13.2-1

**Comment by akram** [comment]
@candalmartin did you find the fix for that?
It is more likely to be related to a token that has expired or a misconfiguration.

**Comment by martincandal** [comment]
@akram we will stop using openshift-sync plugin. Is not stable for us.
Thanks!
